Primeiro projeto de binarizacao de imagems com openCV.

1. Importacao das bibliotecas

In [2]:
import cv2 as cv

2. Vamos ter primeiro uma imagem de um objeto.

In [30]:
img = cv.imread('pelota.jpg')
cv.imshow('pelota', img)
cv.waitKey(0)


-1

2. Vamos passar a imagem a tonalidade cinza

In [31]:
img_cinza = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
cv.imshow('img_cinza', img_cinza)
cv.waitKey(0)

-1

3. Agora aplicamos o filtro Gauseano na imagem

In [32]:
imagem_suave = cv.GaussianBlur (img_cinza,(7,7),0)
cv.imshow('imagem_suave', imagem_suave)
cv.waitKey(0)

-1

4. Fazemos a convercao da imagen ja suavizada pro binario

In [33]:
t, img_bin = cv.threshold(imagem_suave, 160, 255, cv.THRESH_BINARY)
print(t, img_bin)
cv.imshow('img_bin1', img_bin)
cv.waitKey(0)
t_2, img_bin_2 = cv.threshold(imagem_suave, 160, 255, cv.THRESH_BINARY_INV)
cv.imshow('img_bin2', img_bin_2)
cv.waitKey(0)
# Combinacao das dois binarizacoes


160.0 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


-1

5. Combinamos o resultado das dois binarizacoes

In [34]:
import numpy as np
resultado = np.vstack([
    np.hstack([imagem_suave, img_bin]),
    np.hstack([img_bin, cv.bitwise_and(img_cinza ,img_cinza, mask=img_bin)])
])

escala = 0.1  
largura = int(resultado.shape[1] * escala)
altura = int(resultado.shape[0] * escala)
dimencoes = (largura, altura)

resultado_redimensionado = cv.resize(resultado, dimencoes, interpolation=cv.INTER_AREA)

# Resultado redimensionado
cv.imshow('Resultado Redimensionado', resultado_redimensionado)
cv.waitKey(0)
cv.destroyAllWindows()
